config/routes.rb
  #   get 'sign_up/normal', :to => 'users#new'
  #   get 'sign_in', :to => 'devise/sessions#new'
  # end


  resources :profile

  # resources :products
  #post 'products/basic', :to => 'products#create'

  #resources :myshop
  #get 'myshop', :to => 'dashboard#index'
  # get 'myshop/products', :to => 'products#index'

  namespace :myshop do
    root :to => 'dashboard#index'
    resources :products
    resources :dashboard
    resources :shopping_mall_configs
    resources :suppliers
    resources :exchange_rates
    resources :international_delivery_charges
    resources :saved_money_rates
    resources :featured_collections
    resources :featured_products
    resources :featured_product_category
    resources :blog_categories
    resources :blogs

    # get '/featured_product_category', :to => 'featured_product_category#index'
    get '/featured_product_category/new', :to => 'featured_product_category#new'
    # get '/featured_product_category/:id', :to => 'featured_product_category#show'
    # get '/featured_product_category/:id/edit', :to => 'featured_product_category#edit'
    # post '/featured_product_category', :to => 'featured_product_category#create', :as => 'featured_product_categories'
    put '/featured_product_category', :to => 'featured_product_category#update', :as => 'featured_product_categories'

    post 'featured/create'

    get 'orders/change_state/:id', :to => 'orders#change_state', :as => 'change_state'
    get 'orders/take_back_change_state/:id', :to => 'orders#take_back_change_state', :as => 'take_back_change_state'
    get 'orders/take_back_receives', :to => 'orders#take_back_receives', :as => 'take_back_receive'

    put 'orders/cancel/:id', :to => 'orders#cancel', :as => 'order_cancel'
    put 'orders/local_order/:id', :to => 'orders#local_order', :as => 'local_order'
    put 'orders/local_delivery/:id', :to => 'orders#local_delivery', :as => 'local_delivery'
    put 'orders/international_delivery/:id', :to => 'orders#international_delivery', :as => 'international_delivery'
    put 'orders/take_back_complete/:id', :to => 'orders#take_back_complete', :as => 'take_back_complete'
    put 'orders/take_back_cancel/:id', :to => 'orders#take_back_cancel', :as => 'take_back_cancel'
    put 'orders/take_back_confirm/:id', :to => 'orders#take_back_confirm', :as => 'take_back_confirm'
    put 'orders/refund/:id', :to => 'orders#refund', :as => 'refund'
    put 'orders/refund_hold/:id', :to => 'orders#refund_hold', :as => 'refund_hold'

    post 'orders/give_saved_money/:id', :to => 'orders#give_saved_money', :as => 'give_saved_money'

    get 'inquiry_comment', :to => 'inquiry_comment#index', :as => 'inquiry_comment'
    get 'inquiry_comment/:id', :to => 'inquiry_comment#show', :as => 'inquiry_comment_show'
    post 'inquiry_comment/:id', :to => 'inquiry_comment#create', :as => 'inquiry_comment_reply_create'
    delete 'inquiry_comment/:id', :to => 'inquiry_comment#destroy', :as => 'inquiry_comment_reply_destroy'
    get 'profit_withdraw_requests', :to => 'profit_withdraw_requests#index', :as => 'profit_withdraw_requests'
    put 'profit_withdraw_requests/update_state/:id', :to => 'profit_withdraw_requests#update_state', :as => 'profit_withdraw_requests_update_state'

    resources :orders 

  end

  resources :rootshop do
    resources :comments
  end

  # resources :collectionshop do
  #   resources :item
  # end


  get 'collectionshop/:user_id/(:collection_id)', :to => 'collectionshop#show', :as => 'collectionshop'
  post 'collectionshop/follow/:collection_id', :to => 'collectionshop#follow', :as => 'collectionshop_follow'
  post 'collectionshop/unfollow/:collection_id', :to => 'collectionshop#unfollow', :as => 'collectionshop_unfollow'
  get 'collectionshop', :to => 'collectionshop#index', :as => 'collectionshop_index'
  get 'collection_manage', :to => 'collectionshop#collection_manage'
  get 'collection_manage/:collection_id', :to => 'collectionshop#collection_manage_show', :as => 'collection_manage_show'

  #컬렉션 이름 변경
  put 'collection_manage/name_change/:collection_id/', :to => 'collectionshop#collection_name_change', :as => 'collection_name_change'

  #컬렉션 삭제
  delete 'collection_manage/remove_collection/:collection_id', :to => 'collectionshop#remove_collection', :as => 'remove_collection'
  
  #컬렉션 아이템 삭제
  delete 'collection_manage/remove_item/:item_id', :to => 'collectionshop#remove_collection_item', :as => 'remove_collection_item'

  #컬렉션 이미지 변경
  post 'collection_manage/image_update/:collection_id', :to => 'collectionshop#collection_image_update', :as => 'collection_image_update'

  get 'collectionshop/:user_id/item/:item_id', :to => 'item#show', :as => 'collection_item_show'
  post 'collectionshop_comment/:collection_id/comments', :to => 'comments#collectionshop_create', :as => 'collectionshop_comment_add'
  delete 'collectionshop_comment/:collection_id/comments/:comment_id', :to => 'comments#collectionshop_destroy', :as => 'collectionshop_comment_remove'
  get 'collectionshop_comment/:collection_id/comments', :to => 'comments#collectionshop_index', :as => 'collectionshop_comments_index'

  get 'rootshop/:id/inquiry_comment', :to => 'comments#inquiry_comment_index'
  post 'rootshop/:id/inquiry_comment', :to => 'comments#inquiry_comment_create', :as => 'inquiry_comment_create'
  delete 'rootshop/:id/inquiry_comment/:comment_id', :to => 'comments#inquiry_comment_destroy', :as => 'inquiry_comment_destroy'
  # get 'collections/:user_id', :to => 'collections#index', :as => 'collections'
  get 'category_child_2', :to => 'rootshop#category_child_2'
  get 'category_child_3', :to => 'rootshop#category_child_3'

  get 'mypage_inquiry_comment', :to => 'inquiry_comment#index', :as => 'mypage_inquiry_comment'
  delete 'mypage_inquiry_comment/:id', :to => 'inquiry_comment#destroy', :as => 'mypage_inquiry_comment_destroy'

  get 'mypage_saved_money', :to => 'saved_money#index', :as => 'mypage_saved_money'

  post 'mypage_withdrawal_request', :to => 'profits#withdrawal_request', :as => 'mypage_withdrawal_request'

  get 'carts', :to => 'line_items#index', :as => 'cart'
  get 'cart_check', :to => 'line_items#check', :as => 'cart_check'
  post 'carts', :to => 'line_items#create', :as => 'cart_add'
  put 'update_quantity', :to => 'line_items#update_quantity', :as => 'update_quantity'
  put 'update_option', :to => 'line_items#update_option', :as => 'update_option'
  delete 'delete_line_item/:line_item_id', :to => 'line_items#destroy', :as => 'delete_line_item'
  delete 'delete_all_line_item', :to => 'line_items#destroy_all', :as => 'delete_all_line_item'


  get 'orders/new', :to => 'orders#new', :as => 'new_orders'
  post 'orders', :to => 'orders#create', :as => 'orders'
  get 'orders/complete', :to => 'orders#complete', :as => 'complete_order'
  get 'orders/failure_order', :to => 'orders#failure_order', :as => 'failure_order'
  get 'orders', :to => 'orders#index'

  put 'orders/cancel/:id', :to => 'orders#cancel', :as => 'front_order_cancel'
  get 'orders/take_back_request/:id', :to => 'orders#take_back_request', :as => 'front_take_back_request'
  post 'orders/take_back_request/:id', :to => 'orders#create_take_back_request', :as => 'front_create_take_back_request'
  put 'orders/ship_complete/:id', :to => 'orders#ship_complete', :as => 'front_ship_complete'

  get 'profits', :to => 'profits#index'
  post 'profits/withdraw', :to => 'profits#withdrawal_request', :as => 'profits_withdraw'

  

  get 'products', :to => 'otherproducts#index', :as => 'other_products'
  get 'include_collections/:product_id', :to => 'includecollections#index', :as => 'include_collections'

  post 'collection_item_add', :to => 'rootshop#collection_item_add', :as => 'collection_item_add'
  delete 'collection_item_remove', :to => 'rootshop#collection_item_remove', :as => 'collection_item_remove'
  post 'collection_add', :to => 'rootshop#collection_add', :as => 'collection_add'
  delete 'collection_remove/:collection_id', :to => 'rootshop#collection_remove', :as => 'collection_remove'

  get 'zipcodes_search', :to => 'zipcodes#search', :as => 'zipcodes_search'

  get 'mypage', :to => 'mypage#user_info'
  get 'mypage/user_info', :to => 'mypage#user_info'


  post 'upload', :to => 'uploads#create'
  # patch 'upload', :to => 'uploads#create'

  delete 'upload/:id', :to => 'uploads#destroy', :as => 'upload_destroy'
  post 'avatar_update', :to => 'uploads#avatar_update'

  post 'request_user_destroy', :to => 'request_user_destroy#create', :as => 'request_user_destroy'
  delete 'cancel_user_destroy', :to => 'request_user_destroy#destroy', :as => 'cancel_user_destroy'

  get 'users/require_sign_in', :to => 'redirect_myshop_notices#require_sign_in', :as => 'require_sign_in'
  get 'users/require_seller_role', :to => 'redirect_myshop_notices#require_seller_role', :as =>'require_seller_role'
  #get 'myshop', :to => 'myshop#index', constraints: lambda { |request| request.format == "text/html" }
  
  #get 'profile/new', :to => 'profile#new'
  #get 'profile/option', :to => 'profile#option'

  get 'featured', :to => 'featured#index', :as => 'featured_index'
  get 'hot_collections', :to => 'featured#hot_collections', :as => 'hot_collections'

  resources :test
  get 'calculate', :to => 'test#calculate'
  get 'not_available_image', :to => 'test#not_available_image'
  get 'not_available_product', :to => 'test#not_available_product'

  get 'pages/faq' => 'high_voltage/pages#show', id: 'faq'
  get 'pages/clause' => 'high_voltage/pages#show', id: 'clause'

  get 'blogs' => 'blogs#index'
  get 'blogs/:id' => 'blogs#show'

  get 'board/:type' => 'board#index'
  get 'board/:type/new' => 'board#new'
  get 'board/:type/:id' => 'board#show'
  get 'board/:type/:id/edit' => 'board#edit'
  post 'board/:type' => 'board#create', :as => 'board_create'
  delete 'board/:type/:id' => 'board#destroy', :as => 'board_destroy'
  put 'board/:type/:id/edit' => 'board#update', :as => 'board_update'

app/controllers/collectionshop_controller.rb
class CollectionshopController < ApplicationController 


	# layout Proc.new {
	# 	|controller| controller.action_name == 'collection_manage' ? 'rootshop' : 'collection_shop'
	# }

	layout 'rootshop'

	impressionist :actions => [:show]
	before_filter :authenticate_user!, :only => [:follow]

	

	def index
		# @collections = Collection.find_by_sql(
		# 	"select * from collections where (
		# 		select count(1) 
		# 		from collection_items, products
		# 		where (collection_items.collection_id = collections.id and collection_items.deleted_at is null) 
		# 		and (products.id = collection_items.product_id and products.deleted_at is null)
		# 	) > 0"
		# )
		if params[:q].present?

			@collections = Collection.search(params[:q]).where("collection_items_count > 0").page(params[:page]).per(20)
			# @collections = Collection.search(params[:q])
		else
			@collections = Collection.where("collection_items_count > 0").order('updated_at DESC').page(params[:page]).per(20)


		# 	@collections = Collection.find_by_sql(
		# 	"select * from collections where (
		# 		select count(1) 
		# 		from collection_items, products
		# 		where (collection_items.collection_id = collections.id and collection_items.deleted_at is null) 
		# 		and (products.id = collection_items.product_id and products.deleted_at is null)
		# 	) > 0"
		# )
		end

	end

	def show
		user = User.find_by_user_id(params[:user_id])

		unless user
			raise NotFoundUserException
		end

		@collections = Collection.where(:user_id => user.id)
		# @collections =  Collection.select('collections.*, count(collection_items.id) as item_count').
		# 		joins('LEFT JOIN collection_items on collection_items.collection_id = collections.id').
		# 		where(:user_id => user.id).group('collections.id')

		if params[:collection_id].nil?
			@collection = @collections[0]
		else
			@collection = Collection.find(params[:collection_id])
		end

		impressionist(@collection)
		# @collection_items = CollectionItem.where(:collection_id => @collection.id)


		@collection_items = CollectionItem.joins(:product).
			where(
				"collection_items.collection_id = ? 
				and collection_items.deleted_at is null 
				and products.deleted_at is null",
				@collection.id).page(params[:page]).per(20)
			
		# @collection_items = CollectionItem.joins(:product).
		# 	where(
		# 		"collection_items.collection_id = ? ",
		# 		@collection.id).page(params[:page]).per(20)

		# @collection_items = CollectionItem.includes({product: :product_images}).
		# 	where(
		# 		"collection_items.collection_id = ? ",
		# 		@collection.id).page(params[:page]).per(20)


		@comments = @collection.comment_threads.order("created_at DESC").page(1).per(20)
		@comments_count = @collection.comment_threads.count

		# @other_collections = Collection.where('user_id = :user_id and id not in (:id)', 
		# 	:user_id => @collection.user_id, :id => @collection.id).limit(5)
		# @other_collections_all = Collection.where('user_id = :user_id and id not in (:id)', 
		# 	:user_id => @collection.user_id, :id => @collection.id)
		
		# impressionist(@collection)

	rescue ActiveRecord::RecordNotFound
		render 'not_found'

	rescue NotFoundUserException
		render 'not_found'

		
	end

	def collection_manage
		@collections = current_user.collections.includes( :collection_items )
	end

	def collection_manage_show
		@collection = Collection.find(params[:collection_id])
		@collection_items = @collection.collection_items.joins(:product).page(params[:page]).per(10)
		@comments = @collection.comment_threads.order("created_at DESC").page(params[:page]).per(5)
	end

	def collection_name_change
		@collection = Collection.find(params[:collection_id])
		@collection.name = params[:collection_name]
		@collection.save

	end

	def remove_collection_item
		collection_item = CollectionItem.find(params[:item_id])
		# collection = collection_item.collection
		collection_item.destroy

		redirect_to :action => 'collection_manage_show', :collection_id => collection_item.collection_id
	end

	def remove_collection
		collection = Collection.find(params[:collection_id])
		collection.destroy

		redirect_to :action => 'collection_manage'
	end

	def collection_image_update
		collection = Collection.find(params[:collection_id])
		collection.file = params[:collection_image_upload]
		collection.save

		render :json =>  {:small_image_url => collection.featured_small_image_url}
	end
	
	

	def follow
		@collection = Collection.find(params[:collection_id])
		if current_user.following?(@collection)
			# follow = current_user.stop_following(@collection)
			follow = Follow.where(:followable_id => @collection.id, :followable_type => 'Collection', :follower_id => current_user.id, :follower_type => 'User').first
			follow.create_activity key: 'collection.follow_destroy', owner: follow.follower, recipient: follow.followable
			follow.destroy
		
		else
			current_user.follow(@collection)
		end
	end

	def unfollow
		collection = Collection.find(params[:collection_id])
		follow = current_user.stop_following(collection)
	
		# create_activity key: 'collection.follow_destroy', owner: self.follower, recipient: self.followable
	end
end

class NotFoundUserException < StandardError; end

app/views/collectionshop/collection_manage.html.erb
<%= render '/mypage/mypage_menu' %>

<div class="ui bottom attached segment">


<h3 class="ui header">
  컬렉션 관리
</h3>
<div class="ui divider"></div>

<table class="ui celled table segment">
  <thead>
    <tr>
      <th class="six wide" style="text-align: center">컬렉션</th>
      <th class="one wide" style="text-align: center">아이템수</th>
      <th class="two wide" style="text-align: center">컬렉션 수익</th>
      <th class="two wide" style="text-align: center">생성일</th>
      <th class="one wide" style="text-align: center">삭제</th>
    </tr>
  </thead>
  <tbody>
  	<% if @collections.each do |collection| %>
  		<tr>
  			<td><%= image_tag collection.featured_small_image_url, :style => 'width: 70px;'%> <%= link_to collection_manage_show_path collection do %><%= collection.name %><% end %></td>
  			<td style="text-align: right;"><%= collection.collection_items.joins(:product).count %></td>
  			<td style="text-align: right;"><%= price_currency_comma collection.profits.sum("cast(collection_profit as integer)") %></td>
  			<td style="text-align: center;"><%= collection.created_at.strftime("%F %T") %></td>
  			<td style="text-align: center;"><%= link_to remove_collection_path(collection), :class => 'ui button red mini icon', :method => 'delete', :confirm => "컬렉션과 컬렉션이 있는 상품이 모두 삭제됩니다\n삭제하시겠습니까?" do %><i class="trash icon large"></i><% end %></td>
  		</tr>
  	<% end.empty? %>
      <tr><td colspan=5 style="text-align: center;">컬렉션이 존재하지 않습니다.</td></tr>
    <% end %>
  </tbody>
</table>



</div>

app/views/collectionshop/not_found.html.erb
존재하지 않는 상품입니다.

app/views/collectionshop/show.html.erb
<style>

#main {
  position: relative;
}

.collection_items {
  list-style-type: none;
  position: relative; /** Needed to ensure items are laid out relative to this container **/
  margin: 0;
  padding: 0;
}

/**
 * Grid items
 */
.collection_items li {
  width: 175px;
  background-color: #ffffff;
  border: 1px solid #dedede;
          border-radius: 2px;
     -moz-border-radius: 2px;
  -webkit-border-radius: 2px;
  display: none; /** Hide items initially to avoid a flicker effect **/
  /*cursor: pointer;*/
  padding: 15px;
}

.collection_items li.inactive {
  visibility: hidden;
  opacity: 0;
}

.collection_items li img {
  display: block;
}

.tiles li p {
  background-color: 
  color: #666;
  font-size: 12px;
  margin: 7px 0 0 7px;
}

hr {
  display: block;
  padding: 0;
  border: 0;
  border-top: 1px solid #e5e5e5;
}

.product_user_image {
  width: 20px;
  height: 20px;
  border-radius: 2px;
  -moz-border-radius: 2px;
  -webkit-border-radius: 2px;
}

.collection_user_image {
  width: 40px;
  height: 40px;
  border-radius: 2px;
  -moz-border-radius: 2px;
  -webkit-border-radius: 2px;
}

.product_user_id {
  float: left; 
  margin-left: 5px;
  font-size: 12px;
}

.sub.header {
  font-size: 11px;
  /*color: #999;*/
  color: black;
 /* text-overflow: ellipsis;
  white-space: nowrap;
  overflow: hidden;
  min-height: 100px; 
  max-height: 60%; 
  width: 100%*/

}



.product_user_id {
  font-weight: bold;
  color: #4083a9;
}


.product_icons {
  /*margin-top: 10px;*/
  
}


.product_icon {
  color: #8D8D8D;
  /*margin-right: 5px;*/
  text-decoration: none;
  cursor: pointer;
}

.product_icon:hover {
  text-decoration: none;
  color: black;
}

.product_price {
  float: right; 
  margin-top: 5px; 
  font-weight: bold;
}

</style>

<script>
// $(function() {
//    $('.collection_items').imagesLoaded(function() {
//       $('.collection_items li').wookmark({
//         autoResize: false,
//         itemWidth: 205,
//         offset: 10,
//         container: $('#main'),
//         align: 'left'
//       });
//     });
// })

$(function() {
  options = {
    autoResize: true,
    container: $('#main'),
    offset: 10,
    itemWidth: 205,
    align: 'left'
  }

  handler = $('.collection_items li');
  handler.wookmark(options);
})

$(document).ready(function() {
  $("img.lazy").unveil(0, function() {
    $(this).load(function() {
      this.style.opacity = 1;
    });
  });
});

// $(window).load(function() {
//   options = {
//     autoResize: true,
//     container: $('#main'),
//     offset: 10,
//     itemWidth: 205,
//     align: 'left'
//   }

//   handler = $('.collection_items li');
//   handler.wookmark(options);

// });
  


</script>



<div id="container">
  <div class="ui grid">
    <div class="four wide column">
   
      <div class="ui vertical menu fluid">
        <div class="header item" align="center">
       
          <%= image_tag @collection.user.small_image_url, :class => "collection_user_image" %>
          <div style="margin-top: 10px; font-size: 12px;"><span style="color: #4083a9"><%= @collection.user.user_id %></span> 의 컬렉션</div>
        </div>
        <% @collections.each do |collection| %>
          <div class="<% if @collection && @collection.id == collection.id %>active<% end %> red item">
              <%= link_to collectionshop_path(collection.user.user_id, collection), :style => 'font-size: 12px; display:inline-block; width: 190px; overflow: hidden; white-space: nowrap;  text-overflow:ellipsis;' do %>
                <%= collection.name %>

              <% end %>
            <% collection_items = CollectionItem.joins(:product).where(:collection_id => collection.id) %>
            <span class="ui label <% if @collection && @collection.id == collection.id %>red<% end %>">
               <%= collection_items.count %>
            </span>
           


          </div>
        <% end %>
        <% (1..(8 - @collections.size)).each do %>
          <div class="red item" style="font-size: 13px;" align="center">
            컬렉션이 없습니다.
          </div>
        <% end %>
      </div>
   
    </div>
    <div class="twelve wide column">
      <h3 class="ui header">
        <%= @collection.name %>
        <% if user_signed_in? %>
          <% if current_user.id == @collection.user_id %>
            &nbsp;&nbsp;<a class="ui button mini black" href="/collection_manage/<%= @collection.id %>"><i class="setting icon"></i>컬렉션 관리</a>
          <% end %>
        <% end %>
      </h3>
      
      
      

      <div class="ui divider"></div>

      <div  style=" float: left">
        <a class="btn btn-tweet" target="_blank" href="https://twitter.com/intent/tweet?text=<%= @collection.user.user_id %> 님의 <%= @collection.name %> 컬렉션입니다.&url=<%= request.original_url %>&via=quusome.com"><i class="twitter icon" style="font-size: 15px; color: white;"></i></a>
        <a  class="btn btn-facebook" target="_blank" href="http://www.facebook.com/sharer/sharer.php?u=<%= request.original_url %>&t=<%= @collection.user.user_id %> 님의 <%= @collection.name %> 컬렉션입니다."><i class="facebook  icon" style="font-size: 15px; color: white;"></i></a>
        <a class="btn btn-google" target="_blank" href="https://plus.google.com/share?url=<%= request.original_url %>"><i class="google plus  icon" style="font-size: 15px; color: white;"></i></a>
       
        <!-- <%# if current_user %>
          <%#= link_to collectionshop_follow_path(@collection), :class => 'ui button small red', :method => 'post', :remote => true, :id => 'follow_btn' do %>
            <%# if current_user.following?(@collection) %>
              언팔로우
            <%# else %>
              팔로우
            <%# end %>
          <%# end %>
        <%# end %> -->
      </div>

      <div class="ui text menu" style="float: right; margin-top: 5px;">
        <a class="active item" id="collection_tag">
          <i class="block layout icon"></i>컬렉션
        </a>
        <a class="item" id="comment_tag">
          <i class="comment icon"></i>의견(<span id="comments_count"><%= @comments_count %></span>)
        </a>
      
      </div>
      <div id="collection_comments" style="display: none; margin-top: 60px;">
        <%= render 'comments/collection_comments' %>
      </div>

      <div id="main" style="margin-top: 60px;">

        <ul class="collection_items">
          <% @collection_items.each do |item| %>
          <% image_height = (item.product.image_height.to_f * 175) / item.product.image_width.to_f %>

            <li class="collection_item one-edge-shadow">
              <div style="margin-top: -5px; font-size: 12px; background-color: #3F3F3F; color: white; padding: 3px 3px 3px 5px; border-radius: 3px; -moz-border-radius: 3px; -webkit-border-radius: 3px"><%= item.product.title %></div>
                <div class="ui divider" style="margin-top: 5px; margin-bottom: 5px;"></div>

              <div class="item_image">
                
                <%= link_to collection_item_show_path(@collection.user.user_id, item), :class => "uk-overlay-toggle" do %>
                  <div class="uk-overlay" style="height: <%= image_height %>px">
                    <%#= image_tag item.product.featured_rootshop_index_image_url %>
                    <img class="lazy" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-src="<%= item.product.featured_rootshop_index_image_url %>">
                    <div class="uk-overlay-area" style="background: rgba(0,0,0,.1); padding: 5px;">
                </div>
                  </div>

                <% end %>
                <div style="margin-top: 15px;">
                  
                  <div style="float: left;"></div>
                  
                  <div class="product_user_id" style="float: left;">
                    
                  </div>
                  
                </div>
                <div class="product_icons" style="text-align: right; clear: both;">
                    <a href="#" class="product_icon" ><i class="unhide icon"></i><%= item.product.impressionist_count %></a>
                    <a href="#" class="product_icon"><i class="comment icon"></i><%= item.product.reviews.count %></a>
                    <a href="#" class="product_icon"><i class="block layout icon"></i></i><%= item.product.collection_items.count %></a> 
                  </div>

                  <%
                    original_price = item.product.multi_price_final["original"]
                    sale_color_price_min = item.product.multi_price_final["sale_color"].values.min
                  %>

                <div class="product_price">
              <% unless item.product.multi_price_final["sale_color"].empty? %>
                <div style="float:left; padding-right: 10px;">
                  <span style="color:#D95C5C;"><i class="long arrow down icon"></i> <%= ((original_price.to_f - sale_color_price_min.to_f)/original_price.to_f * 100).round  %>%</span>
                </div>
              <% end %>
              <div style="float:left">
              <% unless item.product.multi_price_final["sale_color"].empty? %>

                <i class="won icon"></i><del><%= price_currency_comma original_price %></del><br/>
                
                <i class="won icon"></i><span style="color: #D95C5C"><%= price_currency_comma sale_color_price_min %></span>
              <% else %>
                <i class="won icon"></i><%= price_currency_comma original_price %>
              <% end %>
              </div>

              

            </div>
                
              </div>
              
              
              
            </li>
          <% end %>

         
        </ul>
      </div>

      <div>
        <%= paginate @collection_items %>
      </div>
    </div>
  </div>


</div>