config/routes.rb
# require 'sidekiq/web'
require 'sidetiq/web'

QuusomeS2::Application.routes.draw do

  mount RailsEmailPreview::Engine, at: 'emails'

  # authenticate :user, lambda {|user| user.seller_user? } do
  #   mount PgHero::Engine, at: "pghero"
  # end

  mount Sidekiq::Web, at: '/sidekiq'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {:registrations => "users"}

  root 'featured#index'

  get 'browser', :to => 'browser#index', :as => 'browser'
  
  # get 'users/user_info', :to => 'mypage#user_info'


  # devise_scope :user do
  #   get 'sign_up', :to => 'users#sign_up'
  #   get 'sign_up/seller', :to => 'users#new'
  #   get 'sign_up/normal', :to => 'users#new'
  #   get 'sign_in', :to => 'devise/sessions#new'
  # end


  resources :profile

  # resources :products
  #post 'products/basic', :to => 'products#create'

  #resources :myshop
  #get 'myshop', :to => 'dashboard#index'
  # get 'myshop/products', :to => 'products#index'

  namespace :myshop do
    root :to => 'dashboard#index'
    resources :products
    resources :dashboard
    resources :shopping_mall_configs
    resources :suppliers
    resources :exchange_rates
    resources :international_delivery_charges
    resources :saved_money_rates
    resources :featured_collections
    resources :featured_products
    resources :featured_product_category
    resources :blog_categories
    resources :blogs

    # get '/featured_product_category', :to => 'featured_product_category#index'
    get '/featured_product_category/new', :to => 'featured_product_category#new'
    # get '/featured_product_category/:id', :to => 'featured_product_category#show'
    # get '/featured_product_category/:id/edit', :to => 'featured_product_category#edit'
    # post '/featured_product_category', :to => 'featured_product_category#create', :as => 'featured_product_categories'
    put '/featured_product_category', :to => 'featured_product_category#update', :as => 'featured_product_categories'

    post 'featured/create'

    get 'orders/change_state/:id', :to => 'orders#change_state', :as => 'change_state'
    get 'orders/take_back_change_state/:id', :to => 'orders#take_back_change_state', :as => 'take_back_change_state'
    get 'orders/take_back_receives', :to => 'orders#take_back_receives', :as => 'take_back_receive'

    put 'orders/cancel/:id', :to => 'orders#cancel', :as => 'order_cancel'
    put 'orders/local_order/:id', :to => 'orders#local_order', :as => 'local_order'
    put 'orders/local_delivery/:id', :to => 'orders#local_delivery', :as => 'local_delivery'
    put 'orders/international_delivery/:id', :to => 'orders#international_delivery', :as => 'international_delivery'
    put 'orders/take_back_complete/:id', :to => 'orders#take_back_complete', :as => 'take_back_complete'
    put 'orders/take_back_cancel/:id', :to => 'orders#take_back_cancel', :as => 'take_back_cancel'
    put 'orders/take_back_confirm/:id', :to => 'orders#take_back_confirm', :as => 'take_back_confirm'
    put 'orders/refund/:id', :to => 'orders#refund', :as => 'refund'
    put 'orders/refund_hold/:id', :to => 'orders#refund_hold', :as => 'refund_hold'

    post 'orders/give_saved_money/:id', :to => 'orders#give_saved_money', :as => 'give_saved_money'

    get 'inquiry_comment', :to => 'inquiry_comment#index', :as => 'inquiry_comment'
    get 'inquiry_comment/:id', :to => 'inquiry_comment#show', :as => 'inquiry_comment_show'
    post 'inquiry_comment/:id', :to => 'inquiry_comment#create', :as => 'inquiry_comment_reply_create'
    delete 'inquiry_comment/:id', :to => 'inquiry_comment#destroy', :as => 'inquiry_comment_reply_destroy'
    get 'profit_withdraw_requests', :to => 'profit_withdraw_requests#index', :as => 'profit_withdraw_requests'
    put 'profit_withdraw_requests/update_state/:id', :to => 'profit_withdraw_requests#update_state', :as => 'profit_withdraw_requests_update_state'

    resources :orders 

  end

  resources :rootshop do
    resources :comments
  end

  # resources :collectionshop do
  #   resources :item
  # end


  get 'collectionshop/:user_id/(:collection_id)', :to => 'collectionshop#show', :as => 'collectionshop'
  post 'collectionshop/follow/:collection_id', :to => 'collectionshop#follow', :as => 'collectionshop_follow'
  post 'collectionshop/unfollow/:collection_id', :to => 'collectionshop#unfollow', :as => 'collectionshop_unfollow'
  get 'collectionshop', :to => 'collectionshop#index', :as => 'collectionshop_index'
  get 'collection_manage', :to => 'collectionshop#collection_manage'
  get 'collection_manage/:collection_id', :to => 'collectionshop#collection_manage_show', :as => 'collection_manage_show'

  #컬렉션 이름 변경
  put 'collection_manage/name_change/:collection_id/', :to => 'collectionshop#collection_name_change', :as => 'collection_name_change'

  #컬렉션 삭제
  delete 'collection_manage/remove_collection/:collection_id', :to => 'collectionshop#remove_collection', :as => 'remove_collection'
  
  #컬렉션 아이템 삭제
  delete 'collection_manage/remove_item/:item_id', :to => 'collectionshop#remove_collection_item', :as => 'remove_collection_item'

  #컬렉션 이미지 변경
  post 'collection_manage/image_update/:collection_id', :to => 'collectionshop#collection_image_update', :as => 'collection_image_update'

  get 'collectionshop/:user_id/item/:item_id', :to => 'item#show', :as => 'collection_item_show'
  post 'collectionshop_comment/:collection_id/comments', :to => 'comments#collectionshop_create', :as => 'collectionshop_comment_add'
  delete 'collectionshop_comment/:collection_id/comments/:comment_id', :to => 'comments#collectionshop_destroy', :as => 'collectionshop_comment_remove'
  get 'collectionshop_comment/:collection_id/comments', :to => 'comments#collectionshop_index', :as => 'collectionshop_comments_index'

  get 'rootshop/:id/inquiry_comment', :to => 'comments#inquiry_comment_index'
  post 'rootshop/:id/inquiry_comment', :to => 'comments#inquiry_comment_create', :as => 'inquiry_comment_create'
  delete 'rootshop/:id/inquiry_comment/:comment_id', :to => 'comments#inquiry_comment_destroy', :as => 'inquiry_comment_destroy'
  # get 'collections/:user_id', :to => 'collections#index', :as => 'collections'
  get 'category_child_2', :to => 'rootshop#category_child_2'
  get 'category_child_3', :to => 'rootshop#category_child_3'

  get 'mypage_inquiry_comment', :to => 'inquiry_comment#index', :as => 'mypage_inquiry_comment'
  delete 'mypage_inquiry_comment/:id', :to => 'inquiry_comment#destroy', :as => 'mypage_inquiry_comment_destroy'

  get 'mypage_saved_money', :to => 'saved_money#index', :as => 'mypage_saved_money'

  post 'mypage_withdrawal_request', :to => 'profits#withdrawal_request', :as => 'mypage_withdrawal_request'

  get 'carts', :to => 'line_items#index', :as => 'cart'
  get 'cart_check', :to => 'line_items#check', :as => 'cart_check'
  post 'carts', :to => 'line_items#create', :as => 'cart_add'
  put 'update_quantity', :to => 'line_items#update_quantity', :as => 'update_quantity'
  put 'update_option', :to => 'line_items#update_option', :as => 'update_option'
  delete 'delete_line_item/:line_item_id', :to => 'line_items#destroy', :as => 'delete_line_item'
  delete 'delete_all_line_item', :to => 'line_items#destroy_all', :as => 'delete_all_line_item'


  get 'orders/new', :to => 'orders#new', :as => 'new_orders'
  post 'orders', :to => 'orders#create', :as => 'orders'
  get 'orders/complete', :to => 'orders#complete', :as => 'complete_order'
  get 'orders/failure_order', :to => 'orders#failure_order', :as => 'failure_order'
  get 'orders', :to => 'orders#index'

  put 'orders/cancel/:id', :to => 'orders#cancel', :as => 'front_order_cancel'
  get 'orders/take_back_request/:id', :to => 'orders#take_back_request', :as => 'front_take_back_request'
  post 'orders/take_back_request/:id', :to => 'orders#create_take_back_request', :as => 'front_create_take_back_request'
  put 'orders/ship_complete/:id', :to => 'orders#ship_complete', :as => 'front_ship_complete'

  get 'profits', :to => 'profits#index'
  post 'profits/withdraw', :to => 'profits#withdrawal_request', :as => 'profits_withdraw'

  

  get 'products', :to => 'otherproducts#index', :as => 'other_products'
  get 'include_collections/:product_id', :to => 'includecollections#index', :as => 'include_collections'

  post 'collection_item_add', :to => 'rootshop#collection_item_add', :as => 'collection_item_add'
  delete 'collection_item_remove', :to => 'rootshop#collection_item_remove', :as => 'collection_item_remove'
  post 'collection_add', :to => 'rootshop#collection_add', :as => 'collection_add'
  delete 'collection_remove/:collection_id', :to => 'rootshop#collection_remove', :as => 'collection_remove'

  get 'zipcodes_search', :to => 'zipcodes#search', :as => 'zipcodes_search'

  get 'mypage', :to => 'mypage#user_info'
  get 'mypage/user_info', :to => 'mypage#user_info'


  post 'upload', :to => 'uploads#create'
  # patch 'upload', :to => 'uploads#create'

  delete 'upload/:id', :to => 'uploads#destroy', :as => 'upload_destroy'
  post 'avatar_update', :to => 'uploads#avatar_update'

  post 'request_user_destroy', :to => 'request_user_destroy#create', :as => 'request_user_destroy'
  delete 'cancel_user_destroy', :to => 'request_user_destroy#destroy', :as => 'cancel_user_destroy'

  get 'users/require_sign_in', :to => 'redirect_myshop_notices#require_sign_in', :as => 'require_sign_in'
  get 'users/require_seller_role', :to => 'redirect_myshop_notices#require_seller_role', :as =>'require_seller_role'
  #get 'myshop', :to => 'myshop#index', constraints: lambda { |request| request.format == "text/html" }
  
  #get 'profile/new', :to => 'profile#new'
  #get 'profile/option', :to => 'profile#option'

  get 'featured', :to => 'featured#index', :as => 'featured_index'
  get 'hot_collections', :to => 'featured#hot_collections', :as => 'hot_collections'

  resources :test
  get 'calculate', :to => 'test#calculate'

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	# serialize :options, ActiveRecord::Coders::NestedHstore

	track_who_does_it
	# acts_as_paranoid

  belongs_to :product
  belongs_to :product_option

  # def product
  # 	Product.with_deleted.find(self.product_id)
  # end

  def get_selected_option_item_title(option="color")
    if self.product.is_crawled == 'true'
    	if option == 'color'
    		color_option = self.options.detect {|l| l["option_title"] == "color"}
    		color_option["option_item_title"] if color_option
    	end
    end
  end

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController

	before_filter :authenticate_user!
	layout 'rootshop'

	def index
		@line_items = LineItem.joins("INNER JOIN products ON products.id = line_items.product_id and products.deleted_at is null LEFT OUTER JOIN product_options ON product_options.id = line_items.product_option_id and products.deleted_at is null")
		.where("(line_items.created_by_id = ?)", current_user.id)
		.order('line_items.created_at DESC')

		# @line_items = LineItem.joins("INNER JOIN products ON products.id = line_items.product_id LEFT OUTER JOIN product_options ON product_options.id = line_items.product_option_id")
		# .where("(line_items.created_by_id = ?) and (coalesce(products.amount, 0) > 0 or coalesce(product_options.amount, 0) > 0)", current_user.id)
		# .order('line_items.created_at DESC')

		# @line_items_with_deleted_product = LineItem.joins("INNER JOIN products ON products.id = line_items.product_id LEFT OUTER JOIN product_options ON product_options.id = line_items.product_option_id")
		# .where("line_items.created_by_id = ? and (coalesce(products.amount, 0) = 0 and coalesce(product_options.amount, 0) = 0)", current_user.id)
		# .order('line_items.created_at DESC')

	
	end

	def check
		@line_items = LineItem.where(:created_by_id => current_user.id)
		option_temp_arr = []
		@disavailable = []
		
		@line_items.each do |l|
			l.options.each do |o|
				option_temp_arr << o["option_item_title"]
			end

			
			if l.product.inventory["color*_*#{option_temp_arr[0]}-_-size*_*#{option_temp_arr[1]}"] == 'disavailable'
				p l.product.title
				@disavailable << l.product.title
			end

			option_temp_arr = []
		end
	end

	def create
		if params[:order_type] == 'direct'
			redirect_url = "/orders/new"
			redirect_url += "?order_type=#{params[:order_type]}"
			redirect_url += "&product_id=#{params[:line_item][:product_id]}" 
			if params[:line_item][:product_options_id]
				params[:line_item][:product_options_id].each do |option|
					redirect_url += "&product_options_id[]=#{option}" 
				end
			end
			
			redirect_url += "&quantity=#{params[:line_item][:quantity]}" 
			redirect_url += "&collection_item_id=#{params[:line_item][:collection_item_id]}"

			p redirect_url

			redirect_to redirect_url

		elsif !params[:order_type].present?
			current_line_item = LineItem.where(:product_id => params[:line_item][:product_id], :product_option_id => params[:line_item][:product_option_id]).first
	
			if current_line_item.nil?
				line_item = LineItem.new(line_item_params)
				select_option = params[:line_item][:product_options_id]
				option_str = ""

				if select_option
					select_option.each do |o|
						option_id, option_item_id = o.split('_')
						option = ProductOption.where(:id => option_id.to_i).first
						option_item = ProductOptionItem.where(:id => option_item_id).first
						option_item_title = option_item.title.gsub("'", %q(\\\'))

						# option_str = option_str + "'#{option_id}' => '#{option_item_id}', "
						# option_str = option_str + "'#{option_id}' => {'option_title' => '#{option.title}', 'option_item_id' => '#{option_item.id}', 'option_item_title' => '#{option_item.title}'}, "
						option_str = option_str + "{'option_id' => '#{option.id}', 'option_title' => '#{option.title}', 'option_item_id' => '#{option_item.id}', 'option_item_title' => '#{option_item_title}'},"
					end
			

					line_item.options = eval("[#{option_str}]")
				end
				
				line_item.save
				redirect_to action: 'index'
			else
				current_line_item.update_attributes(:quantity => current_line_item.quantity + params[:line_item][:quantity].to_i)
				redirect_to action: 'index'
			end

		end
	end

	def destroy
		line_item = LineItem.find(params[:line_item_id])
		line_item.destroy
		redirect_to action: 'index'
	end

	def destroy_all

		if params[:cart_ids].present?
			@line_items = LineItem.where(:created_by_id => current_user.id, :id => params[:cart_ids])
		else
			if params[:deleted] == 'true'
				@line_items = (LineItem.joins("INNER JOIN products ON products.id = line_items.product_id LEFT OUTER JOIN product_options ON product_options.id = line_items.product_option_id")
				.where("line_items.created_by_id = ? and (coalesce(products.amount, 0) = 0 and coalesce(product_options.amount, 0) = 0)", current_user.id)).readonly(false)
			else
				@line_items = LineItem.joins("INNER JOIN products ON products.id = line_items.product_id LEFT OUTER JOIN product_options ON product_options.id = line_items.product_option_id")
				.where("(line_items.created_by_id = ?) and (coalesce(products.amount, 0) > 0 or coalesce(product_options.amount, 0) > 0)", current_user.id).readonly(false)
			end
		end
		@line_items.destroy_all
		redirect_to action: 'index'

	end

	def update_quantity
		line_item = LineItem.find(params[:line_item_id])
		line_item.update_attributes(:quantity => params[:quantity])
		redirect_to action: 'index'
	end

	def update_option
		line_item = LineItem.find(params[:line_item_id])
		select_option = params[:line_item][:product_options_id]

		option_str = ""

		select_option.each do |o|
			option_id, option_item_id = o.split('_')
			option = ProductOption.where(:id => option_id.to_i).first
			option_item = ProductOptionItem.where(:id => option_item_id.to_i).first
			option_item_title = option_item.title.gsub("'", %q(\\\'))
			
			line_item.options.each do |lo|
				if lo["option_id"] == option_id
					lo["option_item_id"] = option_item.id.to_s
					lo["option_item_title"] = option_item_title
				end
			end
		end

		line_item.options_will_change!
		line_item.save

		# line_item.update_attributes(:product_option_id => params[:product_option_id])
		redirect_to action: 'index'
	end

	def line_item_params
		params.require(:line_item).permit(:product_id, :product_option_id, :quantity, :collection_item_id)
	end

end

app/views/line_items/_sold_out.html.erb
<br/><br/>
  <h3 class="ui header">
    <i class="attention icon"></i>
    품절인 상품
  </h3>
  <div class="ui divider"></div>


  <table class="ui  table segment">
    <thead>
      <tr>
        <th class="one wide" style="text-align: center"><input type="checkbox" class="cart_check_all"></th>
        <th class="six wide" style="text-align: center">상품</th>
        <th style="text-align: center">옵션</th>
        <th style="text-align: center">수량</th>
        <th class="three wide" style="text-align: center">가격</th>
        <th class="one wide" style="text-align: center">삭제</th>
      </tr>
    </thead>
    <tbody>
      <% if @line_items_with_deleted_product.each do |item| %>
      <%
        option_str = []

        item.options.keys.each do |key|
          product_option = ProductOption.where(:id => key).first
          product_option_item = product_option.product_option_items.where(:id => item.options[key]).first

          option_str.append(product_option.title + ":" + product_option_item.title)
        end
      %>
        <tr>
        <td class="one wide" style="text-align: center"><input type="checkbox" name="cart_ids[]" value="<%= item.id %>"></td>
        <td style="text-align: left">
          <%= image_tag item.product.featured_small_image_url, :style => 'width: 70px; height: 50px;' %> <%= item.product.title %></td>
        <td style="text-align: center">
          <% if option_str.size > 0 %>
            <%= option_str.join(', ') %>
          <% else %>
            없음
          <% end %>
         <!--  <%# unless item.product_option.nil? %>
            <%#= item.product_option.title %>
          <%# else %>
            없음
          <%# end %> -->
        </td>
        <td style="text-align: center">
          <%= item.quantity %>
        </td>
       
        <td style="text-align: center"><i class="uk-icon-krw"></i> <%= price_currency_comma item.product.price.to_i * item.quantity %></td>
        <td style="text-align: center"><%= button_to delete_line_item_path(item), :method => 'delete', :class => 'ui button red mini icon', :confirm => "삭제하시겠습니까?" do %><i class="trash icon large"></i><% end %></td>
      </tr>
    <% end.empty? %>
      <tr><td colspan=5 style="text-align: center;">품절인 상품이 없습니다.</td></tr>
    <% end %>
    </tbody>
  </table>
  <div style="margin-top: 30px;">
    <div style="float:left; margin-right: 10px;">
      <%= form_tag delete_all_line_item_path, :id => 'delete_selected_item_form' do %>
        <input type="hidden" name="selected_line_item[]" id="selected_line_item">
        <a class="ui button blue small delete_selected_item_btn" id="delete_selected_item_btn">선택한 상품 비우기</a>
        
      
      <%= button_to "선택한 상품 비우기", delete_all_line_item_path, :type => 'submit', :method => 'delete', :class => 'ui button blue small', :style => 'display: none;', :id => 'delete_selected_item_submit',:confirm => "선택한 상품을 비우시겠습니까?" %>
      <% end %>
    </div>
    <div style="float:left;">
      <%= button_to "장바구니 비우기", delete_all_line_item_path(:deleted => true), :method => 'delete', :class => 'ui button blue small', :confirm => "장바구니를 비우시겠습니까?" %>
    </div>
  </div>

app/views/line_items/index.html.erb
<style>
  #avatar_image_upload {
    /* Note: display:none on the input won't trigger the click event in WebKit.
      Setting visibility: hidden and height/width:0 works great. */
    visibility: hidden;
    width: 0;
    height: 0;
  }
  #fileSelect {
    /* style the button any way you want */
  }
</style>

<script>
$(function() {
  $('#fileSelect').on('click', function() {
    $('#avatar_image_upload').click();
  });


})
</script>


<%= render '/mypage/mypage_menu' %>

<div class="ui bottom attached segment">


<h3 class="ui header">
  장바구니
</h3>
<div class="ui divider"></div>
<table class="ui  table segment">
  <thead>
    <tr>
      <th class="one wide" style="text-align: center"><input type="checkbox" class="cart_check_all"></th>
      <th class="six wide" style="text-align: center">상품</th>
      <th style="text-align: center">옵션</th>
      <th style="text-align: center">수량</th>
      <th class="three wide" style="text-align: center">가격</th>
      <th class="one wide" style="text-align: center">삭제</th>
    </tr>
  </thead>
  <tbody>

    <% if @line_items.each do |item| %>

    <%
      # option_str = []

      # item.options.keys.each do |key|
      #   product_option = ProductOption.where(:id => key).first
      #   product_option_item = product_option.product_option_items.where(:id => item.options[key]).first

      #   option_str.append(product_option.title + ":" + product_option_item.title)
      # end
    %>

    <tr>
      <% if item.product.inventory %>
        <% item.product.inventory.keys.each do |key| %>
          <input type="hidden" class="inventory" id="<%= key %>" value="<%= item.product.inventory[key] %>">

        <% end %>
      <% end %>
      <td class="one wide" style="text-align: center">
        <input type="checkbox" name="cart_ids[]" value="<%= item.id %>">
        <input type="hidden" class="is_soldout" value="<%= item.product.is_soldout %>" >
      </td>
      <td style="text-align: left">
        <%= image_tag item.product.featured_small_image_url, :style => 'width: 70px;' %> <%= link_to item.product.title, rootshop_path(item.product.id) %></td>
      <td style="text-align: center">
        
        <% if item.product.is_soldout %>
          품절
        <% else %>

          <% unless item.options.nil? %>
            


            <%= form_tag update_option_path, :method => "put" do %>
              <%= hidden_field_tag :line_item_id, item.id %>
              <% item.product.product_options.order("created_at ASC").each do |option| %>

                <% select_option = item.options.detect{|o| o["option_id"] == option.id.to_s} %>
                <% if select_option["option_title"] == 'color' %>
                  <% @selected_color = select_option["option_item_title"] %>
                <% end %>
                <div style="margin-bottom: 5px;">
                  <span><%= option.title %>:</span>
                  <% if option.title == 'size' %>
                    <% option.product_option_items.each do |item| %>
                      <input type="hidden" class="hidden_size_option" title="<%= item.title %>" value="<%= option.id %>_<%= item.id %>">
                    <% end %>
                  <% end %>
                  <% if option.title == 'size' %>
                    <% if item.product.inventory["color*_*#{@selected_color}-_-size*_*#{select_option["option_item_title"]}"] == "disavailable" %>
                      <%= select_option["option_item_title"] %>(품절)
                    <% else %>
                      <%= select_option["option_item_title"] %>
                    <% end %>
                  <% else %>
                    <%= select_option["option_item_title"] %>
                  <% end %>
                  

                  <!--
                  <select title="<%= item.product.title %>" name="line_item[product_options_id][]" class="select_<%= option.title %>" option="<%= option.title %>">
                   
                    <% if option.title == 'size' %>
                      <% option.product_option_items.order("created_at ASC").each do |option_item| %>
                       
                        <% if item.product.inventory["color*_*#{@selected_color}-_-size*_*#{option_item.title}"] == "disavailable" %>
                          <option title="<%= option_item.title %>" value="<%=option.id %>_<%= option_item.id %>" <% if option_item.id.to_s == select_option["option_item_id"] %>selected<% end %> disabled><%= option_item.title %> - 품절</option>
                        <% else %>
                          <option title="<%= option_item.title %>" value="<%=option.id %>_<%= option_item.id %>" <% if option_item.id.to_s == select_option["option_item_id"] %>selected<% end %>><%= option_item.title %></option>

                        <% end %>

                        
                      <% end %>
                     
                    <% else %>
                      <% option.product_option_items.each do |option_item| %>
                        <option title="<%= option_item.title %>" value="<%=option.id %>_<%= option_item.id %>" <% if option_item.id.to_s == select_option["option_item_id"] %>selected<% end %>><%= option_item.title %></option>
                      <% end %>
                    <% end %>
                    
                  </select>
                -->
                </div>
                <% end %>
             
             <!--  <div>
                <%= submit_tag "수정", :class => 'ui button blue mini' %>
              </div> -->
            <% end %>
          <% else %>
            없음
          <% end %>
        <% end %>

      </td>
      <td style="text-align: center">
        <%= form_tag update_quantity_path, :method => "put" do %>
          <input type="number" name="quantity" value="<%= item.quantity %>" min="1" style="width: 50px;">
          <%= hidden_field_tag :line_item_id, item.id %>
          <%= submit_tag "수정", :class => 'ui button blue mini' %>
        <% end %>
      </td>
     
      <td style="text-align: center"><i class="won icon"></i> <%= price_currency_comma item.product.get_price_final(item.get_selected_option_item_title) * item.quantity %></td>
      <td style="text-align: center"><%= button_to delete_line_item_path(item), :method => 'delete', :class => 'ui button red mini icon', :confirm => "삭제하시겠습니까?" do %><i class="trash icon large"></i><% end %></td>
    </tr>
    <% end.empty? %>
      <tr><td colspan=6 style="text-align: center">장바구니에 상품이 없습니다.</td></tr>
    <% end %>
  </tbody>
  <% unless @line_items.empty? %>
  <tfoot>
    <tr >
    <th></th>
    <th style="text-align: center">합계</th>
    <th></th>
    <th style="text-align: center"><%= @line_items.sum { |item| item.quantity } %></th>
    <th style="text-align: center">
      <i class="won icon"></i> <%= price_currency_comma @line_items.sum { |item| item.product.get_price_final(item.get_selected_option_item_title) * item.quantity }%>
    </th>
    <th></th>
  </tr></tfoot>
  <% end %>
</table>



<div style="margin-top: 30px;">
  <% unless @line_items.empty? %>
    <div style="float:left; margin-right: 10px;">
      <div class="ui button blue small" id="order_selected_item_btn">선택한 상품 주문하기</div>
      <%= link_to "선택한 상품 주문하기", new_orders_path, :class => 'ui button blue', :style => 'display: none;', :id => 'order_selected_item' %>
    </div>
    <div style="float:left; margin-right: 10px;">
      <div class="ui button blue small" id="order_item_btn">주문하기</div>
      <%= link_to "주문하기", cart_check_path, :style => 'display: none;', :class => 'ui button blue small', :id => 'order_item_submit', :remote => true %>
    </div>
  <% end %>
  <div style="float:left; margin-right: 10px;">
    <%= form_tag delete_all_line_item_path, :id => 'delete_selected_item_form' do %>
      <input type="hidden" name="selected_line_item[]" id="selected_line_item">
      <a class="ui button blue small delete_selected_item_btn" id="delete_selected_item_btn">선택한 상품 비우기</a>
      
    
    <%= button_to "선택한 상품 비우기", delete_all_line_item_path, :type => 'submit', :method => 'delete', :class => 'ui button blue small', :style => 'display: none;', :id => 'delete_selected_item_submit',:confirm => "선택한 상품을 비우시겠습니까?" %>
    <% end %>
  </div>
  <!-- <div style="float:left;"> -->
    <%#= button_to "장바구니 비우기", delete_all_line_item_path(:deleted => false), :method => 'delete', :class => 'ui button blue small', :confirm => "장바구니를 비우시겠습니까?" %>
  <!-- </div> -->
  <div style="clear:both;"></div>

  
</div>





<%#= render :partial => "sold_out" %>

</div>